apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "queen.api.fullname" . }}
  labels:
    {{- include "queen.api.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.api.replicaCount }}
  selector:
    matchLabels:
      {{- include "queen.api.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
      labels:
        {{- include "queen.api.selectorLabels" . | nindent 8 }}
{{- with .Values.api.podLabels }}
{{ toYaml . | indent 8 }}
{{- end }}
    spec:
      serviceAccountName: {{ include "queen.api.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.api.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.api.securityContext | nindent 12 }}
          image: "{{ .Values.api.image.name }}:{{ .Values.api.image.version }}"
          env:
            - name: FR_INSEE_QUEEN_PERSISTENCE_DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.postgresql.fullnameOverride }}
                  key: password
            - name: FR_INSEE_QUEEN_PERSISTENCE_DATABASE_USER
              value: {{ .Values.postgresql.auth.username | quote}}
            - name: FR_INSEE_QUEEN_PERSISTENCE_DATABASE_HOST
              value: {{ .Values.postgresql.fullnameOverride | quote}}
            - name: FR_INSEE_QUEEN_PERSISTENCE_DATABASE_SCHEMA
              value: {{ .Values.postgresql.auth.database | quote}}
          envFrom:
            - configMapRef:
                name: {{ template "queen.fullname" . }}
          imagePullPolicy: {{ .Values.api.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.api.containerPort }}
              protocol: TCP
          # livenessProbe:
          #   httpGet:
          #     path: /public/healthcheck
          #     port: http
          # readinessProbe:
          #   httpGet:
          #     path: /public/healthcheck
          #     port: http
          resources:
            {{- toYaml .Values.api.resources | nindent 12 }}
      {{- with .Values.api.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.api.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.api.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}