apiVersion: v1
kind: ConfigMap
metadata:
  name: sub2
data:
{{- if .Values.env }}
{{ include "render-value" ( dict "value" .Values.env "context" .) | indent 2}}
{{- end }}
  host : {{ include "render-value" (dict "value" .Values.sub2Host "context" .) }}