apiVersion: v1
kind: Secret
metadata:
  name: knowledge-api-secret
  namespace: {{ .Release.Namespace }}
data:
  mongodb-uri: bW9uZ29kYjovL21vbmdvLWR5bGFuOm1vbmdvZHlsYW5AbW9uZ29kYi0wLm1vbmdvZGItaGVhZGxlc3M6MjcwMTcsbW9uZ29kYi0xLm1vbmdvZGItaGVhZGxlc3M6MjcwMTcsbW9uZ29kYi0yLm1vbmdvZGItaGVhZGxlc3M6MjcwMTcva25vd2xlZGdlP2F1dGhTb3VyY2U9a25vd2xlZGdl # <- base64 encoded "mongodb://mongo-dylan:mongodylan@mongodb-0.mongodb-headless:27017,mongodb-1.mongodb-headless:27017,mongodb-2.mongodb-headless:27017/knowledge?authSource=knowledge"
# mongodb-headless.