{{- if .Values.mongodb.enabled }}
{{- $fullname := include "knowledge.mongodb.fullname" . }}
{{- $db := .Values.mongodb.auth.database }}
{{- $mongoList := include "mongoList" . }}
{{- $user := .Values.mongodb.auth.username }}
{{- $password := .Values.mongodb.auth.password }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $fullname }}-discovery
  annotations:
    knowledge/discovery: "knowledge"
type: Opaque
data:
  mongodb-service: {{ (include "mongoList" .)  | b64enc | quote }}
  mongodb-name: {{ printf "%s" $fullname | b64enc | quote }}
  mongodb-password: {{ $password | b64enc | quote }}
  mongodb-username: {{ $user | b64enc | quote }}
  mongodb-database: {{ $db  | b64enc | quote}}
  mongodb-rootPassword: {{ .Values.mongodb.auth.rootPassword | b64enc | quote }}
  mongodb-uri:  {{  (printf "mongodb://%s:%s@%s/%s" $user $password $mongoList $db ) | b64enc | quote }}
{{- end -}}