{{- if .Values.mongodb.enabled }}
{{- $fullname := include "knowledge.mongodb.fullname" . }}
{{- $db := .Values.mongodb.auth.database }}
{{- $mongoList := include "mongoList" . }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $fullname }}-discovery
  annotations:
    knowledge/discovery: "knowledge"
type: Opaque
data:
  mongodb-service: {{ (include "mongoList" .)  | b64enc | quote }}
  mongodb-name: {{ printf "%s" $fullname | b64enc | quote }}
  mongodb-password: {{ .Values.mongodb.auth.password | b64enc | quote }}
  mongodb-username: {{ .Values.mongodb.auth.username | b64enc | quote }}
  mongodb-database: {{ $db  | b64enc | quote}}
  mongodb-rootPassword: {{ .Values.mongodb.auth.rootPassword | b64enc | quote }}
  mongodb-uri:  {{  (printf "%s/%s" $mongoList $db ) | b64enc | quote }}
{{- end -}}