{{- if .Values.api.enabled }}
{{- if or .Values.api.env .Values.postgresql.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "stromae.api.fullname" . }}
  labels:
    app: {{ template "stromae.api.name" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
{{- if .Values.api.env }}
{{- range $key, $value := .Values.api.env }}
  {{ $key }}: {{ $value | quote }}
{{- end -}}
{{- end -}}
{{- if .Values.postgresql.enabled }}
  FR_INSEE_QUEEN_PERSISTENCE_DATABASE_USER: {{ .Values.postgresql.auth.username | quote}}
  FR_INSEE_QUEEN_PERSISTENCE_DATABASE_HOST: {{ .Values.postgresql.fullnameOverride | quote}}
  FR_INSEE_QUEEN_PERSISTENCE_DATABASE_PASSWORD: {{ .Values.postgresql.auth.password | quote}}
  FR_INSEE_QUEEN_PERSISTENCE_DATABASE_SCHEMA: {{ .Values.postgresql.auth.database | quote}}
{{- end -}}
{{- end -}}
{{- end -}}